In [8]:
import numpy as np

print(np.version.version)

1.21.5


In [49]:
a =  np.random.random((2,3,5));
print(a);
print(a.size);
print(a.shape);

a[0:3][0:2][1]

[[[0.21511267 0.32493067 0.94640293 0.11105575 0.77590567]
  [0.79279194 0.73013988 0.18469523 0.80536587 0.50071   ]
  [0.28316874 0.70797959 0.77123799 0.35876243 0.62991103]]

 [[0.35742912 0.82740861 0.51713086 0.40822923 0.74438684]
  [0.76005348 0.47009466 0.31189957 0.3799173  0.96349338]
  [0.75669672 0.52299693 0.09041985 0.23826674 0.99382432]]]
30
(2, 3, 5)


array([[0.35742912, 0.82740861, 0.51713086, 0.40822923, 0.74438684],
       [0.76005348, 0.47009466, 0.31189957, 0.3799173 , 0.96349338],
       [0.75669672, 0.52299693, 0.09041985, 0.23826674, 0.99382432]])

In [53]:
b = np.ones((5,3,2))
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [54]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

In [55]:
c = np.transpose(b)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [59]:
d = a+c;
print(a);
print("")
print(d);

[[[0.21511267 0.32493067 0.94640293 0.11105575 0.77590567]
  [0.79279194 0.73013988 0.18469523 0.80536587 0.50071   ]
  [0.28316874 0.70797959 0.77123799 0.35876243 0.62991103]]

 [[0.35742912 0.82740861 0.51713086 0.40822923 0.74438684]
  [0.76005348 0.47009466 0.31189957 0.3799173  0.96349338]
  [0.75669672 0.52299693 0.09041985 0.23826674 0.99382432]]]

[[[1.21511267 1.32493067 1.94640293 1.11105575 1.77590567]
  [1.79279194 1.73013988 1.18469523 1.80536587 1.50071   ]
  [1.28316874 1.70797959 1.77123799 1.35876243 1.62991103]]

 [[1.35742912 1.82740861 1.51713086 1.40822923 1.74438684]
  [1.76005348 1.47009466 1.31189957 1.3799173  1.96349338]
  [1.75669672 1.52299693 1.09041985 1.23826674 1.99382432]]]


In [61]:
e = a*c;
print(a);
print("")
print(e);


[[[0.21511267 0.32493067 0.94640293 0.11105575 0.77590567]
  [0.79279194 0.73013988 0.18469523 0.80536587 0.50071   ]
  [0.28316874 0.70797959 0.77123799 0.35876243 0.62991103]]

 [[0.35742912 0.82740861 0.51713086 0.40822923 0.74438684]
  [0.76005348 0.47009466 0.31189957 0.3799173  0.96349338]
  [0.75669672 0.52299693 0.09041985 0.23826674 0.99382432]]]

[[[0.21511267 0.32493067 0.94640293 0.11105575 0.77590567]
  [0.79279194 0.73013988 0.18469523 0.80536587 0.50071   ]
  [0.28316874 0.70797959 0.77123799 0.35876243 0.62991103]]

 [[0.35742912 0.82740861 0.51713086 0.40822923 0.74438684]
  [0.76005348 0.47009466 0.31189957 0.3799173  0.96349338]
  [0.75669672 0.52299693 0.09041985 0.23826674 0.99382432]]]


d_max = np.amax(d);
d_min = np.amin(d);
d_mean = np.mean(d);
print(d_max);
print(d_min);
print(d_mean);

In [100]:
f = np.zeros((2,3,5))
print(f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [119]:
d = ([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

d_max = np.amax(d);
d_min = np.amin(d);
d_mean = np.mean(d);
print(d_max);
print(d_min);
print(d_mean);

f = np.zeros((2,3,5))

a,b,c = f.shape

for i in range(a):
    for j in range(b):
        for k in range(c):
            if d[i][j][k]>d_min and d[i][j][k]<d_mean:
                f[i][j][k] = 75;
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50;
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0;
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100;
                
                
print(f);


1.97066381
1.00656599
1.6175069086666667
[[[  0.   0.   0.  75.   0.]
  [  0.   0.  75.  75.  75.]
  [  0.  75.   0.   0.   0.]]

 [[ 75.  75.  75.  75. 100.]
  [  0.   0.   0.   0.   0.]
  [ 75.   0.   0.   0.   0.]]]


5